### ISSUE TITLE
What is the progress of this project? 

### ISSUE THREAD

**Issue by leyou240** [dubbo/dubbo-dotnet#4]
Our company is interested in dubbo who also used dotnet platform.  And want to use dubbo.net.
I want to know the progress and do some contribution. thx
@ralf0131 @kimmking

**Comment by ralf0131** [comment]
Hi, welcome!

I think this project is still under development. If you are interested please feel free to contribute!
p.s. This project will be transferred to Apache soon. You can send pull request, but I recommend to merge it after the transition. Because the contribution will be counted as contribution to Apache Dubbo.

**Comment by Rwing** [comment]
I think this project is dead now, it hasn't updated a line code in two years!

**Comment by leyou240** [comment]
没有进度，建议删除此项目吧。没有存在的意义了
